spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: /h2
# static h2 settings
  datasource:
    username: sa
    url: jdbc:h2:./devdb2;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver

# in memory h2 settings
#  datasource:
#    username: sa
#    url: jdbc:h2:mem:devdb2;AUTO_SERVER=TRUE
#    driverClassName: org.h2.Driver


# execute once only
#  sql:
#    init:
#      schema-locations: classpath:/data.sql
#      mode: always

server:
  port: 8080



