spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: /h2

# in memory h2 settings
  datasource:
    username: sa
    url: jdbc:h2:mem:devdb3
    driverClassName: org.h2.Driver


server:
  port: 8081
